// Spacing audit on top of the pixel-diff artifacts (run pixel-diff.mjs first).
// For every section crop it measures the side margins, the inner top/bottom padding, the height and the gaps
// between items in a row, for the Figma reference and for the build, and flags differences ≥ spacingFlag px.
// The section background is the most frequent colour along the left and right edge columns.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PNG } from 'pngjs';
import { loadConfig } from './config.mjs';

const config = loadConfig();
const DIFF_DIR = join(config.dir, 'diff');
const OUT = join(config.dir, 'SPACING-AUDIT.md');
const FLAG = config.spacingFlag;
const TOLERANCE = 24; // summed RGB distance that still counts as background

const resultsFile = join(DIFF_DIR, 'results.json');
if (!existsSync(resultsFile)) throw new Error(`No ${resultsFile}: run pixel-diff.mjs first.`);
const results = JSON.parse(readFileSync(resultsFile, 'utf8'));
const fileName = (name) => name.replace(/[^\p{L}\p{N}_-]+/gu, '-');

function background(png) {
  const counts = new Map();
  for (let y = 0; y < png.height; y++) {
    for (const x of [0, png.width - 1]) {
      const i = (y * png.width + x) * 4;
      const key = `${png.data[i]},${png.data[i + 1]},${png.data[i + 2]}`;
      counts.set(key, (counts.get(key) ?? 0) + 1);
    }
  }
  const [top] = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  return top ? top[0].split(',').map(Number) : [255, 255, 255];
}

function measure(png) {
  const bg = background(png);
  const isContent = (x, y) => {
    const i = (y * png.width + x) * 4;
    return (
      Math.abs(png.data[i] - bg[0]) + Math.abs(png.data[i + 1] - bg[1]) + Math.abs(png.data[i + 2] - bg[2]) >
      TOLERANCE
    );
  };
  let left = png.width;
  let right = -1;
  let top = png.height;
  let bottom = -1;
  const columns = new Array(png.width).fill(false);
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) {
      if (!isContent(x, y)) continue;
      columns[x] = true;
      if (x < left) left = x;
      if (x > right) right = x;
      if (y < top) top = y;
      if (y > bottom) bottom = y;
    }
  }
  if (right < 0) return null;
  // Gaps: runs of empty columns strictly inside the content box.
  const gaps = [];
  let run = 0;
  for (let x = left; x <= right; x++) {
    if (!columns[x]) run++;
    else if (run > 0) {
      if (run >= 4) gaps.push(run);
      run = 0;
    }
  }
  return { left, right: png.width - 1 - right, top, bottom: png.height - 1 - bottom, gaps };
}

const cell = (expected, actual) => {
  const delta = actual - expected;
  const sign = delta > 0 ? '+' : '';
  return `${expected} / ${actual} (${sign}${delta})${Math.abs(delta) >= FLAG ? ' ←' : ''}`;
};

const lines = [
  '# Spacing audit',
  '',
  `Generated by spacing-audit.mjs from the pixel-diff artifacts. Cells: reference / build (delta); \`←\` marks a difference ≥ ${FLAG} px.`,
  'Height is the section height: the sections file for the reference, the DOM bounding box for the build.',
  '',
];
let flagged = 0;
for (const screen of results) {
  lines.push(`## ${screen.id}${screen.node ? ` (${screen.node})` : ''}`, '');
  lines.push('| Section | Left | Right | Top padding | Bottom padding | Height | Gaps in a row (reference → build) |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- |');
  screen.sections.forEach((section, index) => {
    if (section.missing) {
      lines.push(`| ${section.name} | — | — | — | — | — | missing in DOM |`);
      return;
    }
    const base = join(DIFF_DIR, `${screen.id}-${screen.width}-${index}-${fileName(section.name)}`);
    const expected = measure(PNG.sync.read(readFileSync(`${base}-expected.png`)));
    const actual = measure(PNG.sync.read(readFileSync(`${base}-actual.png`)));
    if (!expected || !actual) {
      lines.push(`| ${section.name} | — | — | — | — | — | empty section |`);
      return;
    }
    const row = [
      cell(expected.left, actual.left),
      cell(expected.right, actual.right),
      cell(expected.top, actual.top),
      cell(expected.bottom, actual.bottom),
      cell(section.figma.height, section.dom.height),
    ];
    flagged += row.filter((value) => value.endsWith('←')).length;
    const gaps = `${expected.gaps.join(', ') || '—'} → ${actual.gaps.join(', ') || '—'}`;
    lines.push(`| ${section.name} | ${row.join(' | ')} | ${gaps} |`);
  });
  lines.push('');
}
writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote ${OUT}: ${flagged} value(s) off by ≥ ${FLAG} px.`);
